name: MGNoteblockBlitz
main: com.comze_instancelabs.noteblockblitz.Main
version: 1.0.0
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   nb:
      description: Main command
      usage: /noteblockblitz [action]
      aliases: [noteblockblitz, mgnoteblockblitz, nbb]
