name: MGNoteblockBlitz
main: com.comze_instancelabs.noteblockblitz.Main
version: ${version}
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   nb:
      description: Main command
      usage: /noteblockblitz [action]
      aliases: [noteblockblitz, mgnoteblockblitz, nbb]
